{"asctime":"2020-09-27 01:25:25,097", "levelname":"INFO", "threadName":"139892691389216", "filename":"handlelogs.py", "module":"handlelogs", "lineno":"123", "funcName":"__call__","message":"system-auto"}
{"asctime":"2020-09-27 01:25:25,250", "levelname":"INFO", "threadName":"139892691389216", "filename":"handlelogs.py", "module":"handlelogs", "lineno":"123", "funcName":"__call__","message":"system-auto"}
{"asctime":"2020-09-27 01:25:55,480", "levelname":"INFO", "threadName":"139892738071880", "filename":"autoreload.py", "module":"autoreload", "lineno":"222", "funcName":"trigger_reload","message":"/usr/src/api/vuebackend/settings.py changed, reloading."}
{"asctime":"2020-09-27 01:25:56,069", "levelname":"INFO", "threadName":"140198622883144", "filename":"autoreload.py", "module":"autoreload", "lineno":"598", "funcName":"run_with_reloader","message":"Watching for file changes with StatReloader"}
{"asctime":"2020-09-27 01:27:11,148", "levelname":"INFO", "threadName":"140198622883144", "filename":"autoreload.py", "module":"autoreload", "lineno":"222", "funcName":"trigger_reload","message":"/usr/src/api/vuebackend/settings.py changed, reloading."}
{"asctime":"2020-09-27 01:27:54,682", "levelname":"ERROR", "threadName":"139697519962912", "filename":"log.py", "module":"log", "lineno":"228", "funcName":"log_response","message":"Internal Server Error: /api/get_logs/"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/api/api/views.py", line 385, in get
    l_split = json.loads(line.strip('\n'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
{"asctime":"2020-09-27 01:32:13,208", "levelname":"INFO", "threadName":"140046265331016", "filename":"autoreload.py", "module":"autoreload", "lineno":"598", "funcName":"run_with_reloader","message":"Watching for file changes with StatReloader"}
{"asctime":"2020-09-27 01:34:21,360", "levelname":"INFO", "threadName":"140046265331016", "filename":"autoreload.py", "module":"autoreload", "lineno":"222", "funcName":"trigger_reload","message":"/usr/src/api/vuebackend/settings.py changed, reloading."}
